# Generated by Django 4.2.6 on 2023-12-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('password', models.IntegerField()),
                ('re_password', models.IntegerField()),
            ],
        ),
    ]
